### ISSUE TITLE
Deno Deploy Internal Server Error

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [ascorbic/og-edge#7]
When deploying to Deno deploy, I get a Internal Server Error. I used the example code in the readme and this what happens when deploying to Deno deploy.

### Internal Server Error

```
ReferenceError: h is not defined
    at Server.handler (file:///src/index.tsx:4:5)
    at Server.#respond (https://deno.land/std@0.140.0/http/server.ts:219:43)
    at Server.#serveHttp (https://deno.land/std@0.140.0/http/server.ts:253:26)
```

### Code Used

```tsx

import { serve } from "https://deno.land/std@0.140.0/http/server.ts";
import React from "https://esm.sh/react@18.2.0";
import { ImageResponse } from "https://deno.land/x/og_edge/mod.ts";

async function handler(req: Request) {
  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: 128,
        background: "lavender",
      }}
    >
      Hello!
    </div>,
  );
}

serve(handler);
```

**Comment by ascorbic** [comment]
You might need to follow these instructions: https://deno.land/manual@v1.31.2/advanced/jsx_dom/jsx

**Comment by Isaiah-Hamilton** [comment]
Thank you @ascorbic, I was able to get it to work by using Preact instead of React. here's is the new code that got the error to go away.

```tsx
/** @jsx h */
import { h } from "https://esm.sh/preact";
import { serve } from "https://deno.land/std@0.140.0/http/server.ts";
import { ImageResponse } from "https://deno.land/x/og_edge/mod.ts";

async function handler(req: Request) {
  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: 128,
        background: "lavender",
      }}
    >
      Hello!
    </div>,
  );
}

serve(handler);
```
